(in-package :visp)

(defun print-help ()
  (format t "~%visp - minimal ffmpeg wrapper written in Common Lisp~%~%")
  (format t "Usage:~%  ./visp.ros --input <file> [options]~%~%")
  (format t "Required:~%  --input <file>       Input video file~%~%")
  (format t "Optional:~%")
  (format t "  --res <label>        Set output resolution (hd, fhd, 2k, 4k, etc)~%")
  (format t "  --half               Downscale to half the input resolution~%")
  (format t "  --fps <number>       Set output framerate (e.g., 30)~%")
  (format t "  --codec <type>       Set codec (h264, h265, prores, hap, vp8, vp9)~%")
  (format t "  --mono               Convert to grayscale (h264/h265 only)~%")
  (format t "  --reverse            Reverse video playback (audio not affected)~%")
  (format t "  --loop <n>           Loop playback n times (e.g., 3 = 4 total plays)~%")
  (format t "  --mute               Remove audio track~%")
  (format t "  --dry-run            Show ffmpeg command without running it~%")
  (format t "  --help               Show this help message~%~%")
  (format t "Example:~%  ./visp.ros --input movie.mp4 --res fhd --codec h264 --mono --mute~%"))
