(in-package :visp)

(defun print-help ()
  (format t "~%visp - minimal ffmpeg wrapper written in Common Lisp~%~%")
  (format t "Usage:~%  ./visp.ros --input <file> [options]~%~%")
  (format t "Required:~%  --input <file>       Input video file~%~%")
  (format t "Optional:~%")
  (format t "  --res <label>        Resolution (hd, fhd, 2k, 4k, etc)~%")
  (format t "  --half               Downscale to half the input resolution~%")
  (format t "  --fps <number>       Output framerate (e.g., 30)~%")
  (format t "  --codec <type>       Codec to use (h264, h265, prores, hap, vp8, vp9)~%")
  (format t "  --mute               Remove audio track~%")
  (format t "  --loop <n>           Loop input video n times (e.g., 3 → plays 4 times)~%")
  (format t "  --reverse            Create a reversed playback (video only)~%")
  (format t "  --dry-run            Print ffmpeg command without executing it~%")
  (format t "  --help               Show this help message~%~%")
  (format t "Example:~%  ./visp.ros --input movie.mp4 --res fhd --codec h264 --mute~%"))
